site_name: ObiWanLansi
site_url: ""
site_description: ObiWanLansi
site_author: ObiWanLansi
use_directory_urls: false
docs_dir: "./docs"
plugins: []
theme:
    name: readthedocs
    nav_style: dark
    #locale: de
